drop table if exists quote CASCADE;

create table quote (
    id bigint generated by default as identity,
    close_value double,
    open_value double,
    symbol varchar(255),
    timestamp timestamp,
    primary key (id)
);
